
name: "Codecov"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Build
      run: |
        brew install gcc@15 lcov ninja binutils
        brew link --force binutils
        cmake -B build -GNinja -DCMAKE_CXX_COMPILER=g++-15 -DCMAKE_CXX_FLAGS="--coverage" -DCMAKE_EXE_LINKER_FLAGS="--coverage"
        cmake --build build

    - name: Run tests
      working-directory: ${{github.workspace}}/build
      run: ctest

    - name: Generate coverage report
      working-directory: ${{github.workspace}}/build/test/CMakeFiles/test-flux.dir
      run: |
        lcov --directory . --capture --gcov gcov-15 --output-file coverage.info
        lcov --remove coverage.info '*/test/*' --output-file coverage.info

    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      with:
        files: ${{github.workspace}}/build/test/CMakeFiles/test-flux.dir/coverage.info
        token: ${{secrets.CODECOV_TOKEN}}
        verbose: true

