name: Linux CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [GCC-12, GCC-13, GCC-14, GCC-15, Clang-17, Clang-18, Clang-19, Clang-20, Clang-21]
        test_with: [Headers, Module]
        build_type: [Debug, Release]

        exclude:
          - compiler: GCC-12
            test_with: Module
          - compiler: GCC-13
            test_with: Module
          - compiler: GCC-14
            test_with: Module
          - compiler: GCC-15
            test_with: Module
          - compiler: Clang-17
            test_with: Module

        include:
          - compiler: GCC-12
            cxx: g++-12
            install: |
              brew install gcc@12 ninja binutils
              brew link --force binutils
          - compiler: GCC-13
            cxx: g++-13
            install: |
              brew install gcc@13 ninja binutils
              brew link --force binutils
          - compiler: GCC-14
            cxx: g++-14
            install: |
              brew install gcc@14 ninja binutils
              brew link --force binutils
          - compiler: GCC-15
            cxx: g++-15
            install: |
              brew install gcc@15 ninja binutils
              brew link --force binutils
          - compiler: Clang-17
            cxx: $(brew --prefix llvm@17)/bin/clang++
            install: |
              brew install llvm@17 ninja binutils
              brew link --force binutils
          - compiler: Clang-18
            cxx: $(brew --prefix llvm@18)/bin/clang++
            install: |
              brew install llvm@18 ninja binutils
              brew link --force binutils
          - compiler: Clang-19
            cxx: $(brew --prefix llvm@19)/bin/clang++
            install: |
              brew install llvm@19 ninja binutils
              brew link --force binutils
          - compiler: Clang-20
            cxx: $(brew --prefix llvm@20)/bin/clang++
            install: |
              brew install llvm@20 ninja binutils
              brew link --force binutils
          - compiler: Clang-21
            cxx: $(brew --prefix llvm@21)/bin/clang++
            install: |
              brew install llvm@21 ninja binutils
              brew link --force binutils

    steps:
    - uses: actions/checkout@master

    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}

    - name: Configure
      run: |
        cmake -B build -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
              -DCMAKE_CXX_EXTENSIONS=Off \
              -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
              -DFLUX_BUILD_MODULE=${{matrix.test_with == 'Module'}} \
              -DFLUX_BUILD_TESTS_USING_MODULE=${{matrix.test_with == 'Module'}}

    - name: Build
      run: cmake --build build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
