# Based on macos.yml from {fmt}
# https://github.com/fmtlib/fmt/blob/master/.github/workflows/macos.yml

name: MacOS CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-15
    strategy:
      matrix:
        compiler: [AppleClang, LLVM-Clang-16, LLVM-Clang-17, LLVM-Clang-18, LLVM-Clang-19, LLVM-Clang-20, LLVM-Clang-21]
        test_with: [Headers, Module]
        build_type: [Debug, Release]

        exclude:
          - compiler: AppleClang
            test_with: Module
          - compiler: LLVM-Clang-16
            test_with: Module

        include:
          - compiler: AppleClang
            cxx: clang++
            install: |
              brew install ninja
          - compiler: LLVM-Clang-16
            cxx: $(brew --prefix llvm@16)/bin/clang++
            install: |
              brew install llvm@16 ninja
          - compiler: LLVM-Clang-17
            cxx: $(brew --prefix llvm@17)/bin/clang++
            install: |
              brew install llvm@17 ninja
          - compiler: LLVM-Clang-18
            cxx: $(brew --prefix llvm@18)/bin/clang++
            install: |
              brew install llvm@18 ninja
          - compiler: LLVM-Clang-19
            cxx: $(brew --prefix llvm@19)/bin/clang++
            install: |
              brew install llvm@19 ninja
          - compiler: LLVM-Clang-20
            cxx: $(brew --prefix llvm@20)/bin/clang++
            install: |
              brew update
              brew install llvm@20 ninja
          - compiler: LLVM-Clang-21
            cxx: $(brew --prefix llvm@21)/bin/clang++
            ldflags: -L$(brew --prefix llvm@21)/lib/c++
            install: |
              brew update
              brew install llvm@21 ninja


    steps:
    - uses: actions/checkout@master

    - name: Create Build Environment
      run: |
        ${{matrix.install}}

    - name: Configure
      run: |
        cmake -B build -GNinja \
              -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
              -DCMAKE_EXE_LINKER_FLAGS=${{matrix.ldflags}} \
              -DCMAKE_OSX_SYSROOT=$(xcrun --sdk macosx --show-sdk-path) \
              -DCMAKE_CXX_EXTENSIONS=Off \
              -DCMAKE_COMPILE_WARNING_AS_ERROR=On \
              -DCMAKE_LINK_WARNING_AS_ERROR=On \
              -DFLUX_BUILD_BENCHMARKS=${{matrix.build_type == 'Release'}} \
              -DFLUX_BUILD_MODULE=${{matrix.test_with == 'Module'}} \
              -DFLUX_BUILD_TESTS_USING_MODULE=${{matrix.test_with == 'Module'}}

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}}
      env:
        CTEST_OUTPUT_ON_FAILURE: True
